In [3]:
import numpy as np
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
B.shape

(4, 1)

In [5]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(9.0).reshape((3,3))
print(x1,x2)
np.multiply(x1, x2)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]] [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


array([[ 0.,  1.,  4.],
       [ 9., 16., 25.],
       [36., 49., 64.]])